In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [3]:
dim= np.array((([[1, 2, 7,3], [4, 9, 6,4], [5, 2, 3,5]]),
                
([[1, 2, 3,5], [4, 5, 6,4],[1, 2, 3,8]]), ([[6, 2, 3,7], [4, 5, 6,8], [6, 2, 3,4]]),([[7, 2, 3,4], [9, 5, 6,8], [1, 2, 3,9]])))
dim

array([[[1, 2, 7, 3],
        [4, 9, 6, 4],
        [5, 2, 3, 5]],

       [[1, 2, 3, 5],
        [4, 5, 6, 4],
        [1, 2, 3, 8]],

       [[6, 2, 3, 7],
        [4, 5, 6, 8],
        [6, 2, 3, 4]],

       [[7, 2, 3, 4],
        [9, 5, 6, 8],
        [1, 2, 3, 9]]])

In [4]:
dim.dtype

dtype('int32')

In [29]:
len(dim)

4

In [30]:
dim.shape

(4, 3, 4)

In [31]:
dim.ndim

3

In [34]:
dim[0]
dim[2]
dim[3]

array([[7, 2, 3, 4],
       [9, 5, 6, 8],
       [1, 2, 3, 9]])

In [21]:
dim[1]

array([[1, 2, 3, 5],
       [4, 5, 6, 4],
       [1, 2, 3, 8]])

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [5]:
arr = np.arange(20)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [17]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1, 3])

2nd element on 1st row:  9


In [12]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [18]:
import pandas as pd

In [20]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr.shape)
print(arr.ndim)

6
(2, 2, 3)
3


In [19]:
import pandas as pd
# create a simple dataset of people
data = {'Name': ["John", "Anna", "Peter", "Linda"],
'Location' : ["New York", "Paris", "Berlin", "London"],
'Age' : [24, 13, 53, 33]
}
data_pandas = pd.DataFrame(data)
data_pandas

Name  Location  Age
0   John  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53
3  Linda    London   33

In [5]:
# create a 2d numpy array with a diagonal of ones, and zeros everywhere else
eye = np.eye(4)
print("Numpy array:\n%s" % eye)

Numpy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
df = np.eye(6)
print("Numpy array:\n%s" % df)

Numpy array:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [16]:
import numpy as np
from scipy.sparse import csr_matrix

In [17]:
# convert the numpy array to a scipy sparse matrix in CSR format
# only the non-zero entries are stored
sparse_matrix = csr_matrix(eye)
print("\nScipy sparse CSR matrix:\n%s" % sparse_matrix)


Scipy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [30]:
from sklearn.datasets import load_iris
iris = load_iris()

In [31]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [32]:
print(iris['DESCR'][:400] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
               
...


In [1]:
import numpy as np

In [2]:
# Get the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [5]:
import numpy as np

#DTYPE
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )


In [9]:
nic = np.array([1,2,3,4,5], dtype='S')
nic

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [10]:
nic.dtype

dtype('S1')

In [11]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])



In [21]:
newarr = arr.astype('int')



In [22]:
print(newarr)


[1 2 3]


In [23]:
print(newarr.dtype)

int32


## Numpy Random Seed

In [35]:

#This keeps the random numbers constant and not changing
np.random.seed(4)
import numpy as np
Random_4 = np.random.random((5,3))
Random_4

array([[0.96702984, 0.54723225, 0.97268436],
       [0.71481599, 0.69772882, 0.2160895 ],
       [0.97627445, 0.00623026, 0.25298236],
       [0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224]])

In [21]:
#Running the same code but using the Randit func
np.random.seed(42)
import numpy as np
Random_5 = np.random.randint(10, size=(5,3))
Random_5

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

## View Arrays and Matrices 

In [11]:
#Find a unique element in an array using the np.unique func
np.unique(Random_5)


array([2, 3, 4, 5, 6, 7, 9])

In [17]:
#Let us retrun indices 
u, indices = np.unique(Random_5, return_index=True)
u


array([2, 3, 4, 5, 6, 7, 9])

In [37]:
#Try another here
x, indices = np.unique(Random_4, return_index=True)
x

array([0.00623026, 0.16384224, 0.19768507, 0.2160895 , 0.25298236,
       0.43479153, 0.54723225, 0.69772882, 0.71481599, 0.77938292,
       0.86299324, 0.96702984, 0.97268436, 0.97627445, 0.98340068])

### Reconstruct the input array from the unique values and inverse

In [39]:
u, indices = np.unique(Random_4, return_inverse=True)
u

array([0.00623026, 0.16384224, 0.19768507, 0.2160895 , 0.25298236,
       0.43479153, 0.54723225, 0.69772882, 0.71481599, 0.77938292,
       0.86299324, 0.96702984, 0.97268436, 0.97627445, 0.98340068])

In [40]:
##Reconstruct the input values from the unique values and counts:
values, counts = np.unique(Random_4, return_counts=True)
values

array([0.00623026, 0.16384224, 0.19768507, 0.2160895 , 0.25298236,
       0.43479153, 0.54723225, 0.69772882, 0.71481599, 0.77938292,
       0.86299324, 0.96702984, 0.97268436, 0.97627445, 0.98340068])